added the data field on the sign transaction display
ElrondNetwork/ledger-elrond pull request #17
Opened 2020-09-11 15:47 UTC by mihaib79

2020-09-11 17:33 UTC, andreibancioiu commented on src/signTx.c
> +//            if (len % 4 != 0) {
Remove this perhaps?

2020-09-11 17:33 UTC, andreibancioiu commented on src/signTx.c
> +            if (!base64decode(tx_context.data, str, len)) {
The decoding might contain non printable characters (since decoding assumes an original ASCII-equivalent encoding, which isn't necessarily the case). Perhaps replace non-printable characters with something like `?`.

At this point, I do not have a recommendation on how to deal with UTF-8 strings... Does ledger support printing UTF-8 on the screen?

2020-09-11 17:33 UTC, andreibancioiu commented on src/signTx.h
> +#define MAX_DATA_SIZE         512   // 512 in base64 = 384 in ASCII
So we do not allow one to sign transactions when encoded data length > 512? We didn't have this constraint before. Or did we?

Anyway, the thing is that the data field can be (is) UTF-8.

2020-09-11 18:17 UTC, mihaib79 commented on src/signTx.h
> +#define MAX_DATA_SIZE         512   // 512 in base64 = 384 in ASCII
We did have (and still do) a limitation to the entire tx json to 1024 bytes. I tried to allocate more RAM to the variable containing the data field and the app becomes unstable. Increasing the 1024 value throws an out of SRAM error.

2020-09-11 18:18 UTC, mihaib79 commented on src/signTx.c
> +            if (!base64decode(tx_context.data, str, len)) {
Good idea to replace all chars lower than 32 and higher than 128 with '?'

2020-09-11 18:24 UTC, mihaib79 commented on src/signTx.c
> +//            if (len % 4 != 0) {
Done.

2020-09-11 18:24 UTC, mihaib79 commented on src/signTx.c
> +    return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c == '+') || (c == '/') || (c == '=') || isdigit(c);
Done.

2020-09-11 18:25 UTC, mihaib79 commented on src/signTx.c
> +static char base64decode_byte(char c) {
It's my own implementation :-/

2020-09-11 18:25 UTC, mihaib79 commented on src/signTx.c
> +static bool base64decode(char *decoded, char *source, size_t len) {
It's my own implementation :-/

2020-09-11 18:46 UTC, mihaib79 commented on src/signTx.c
> +    tx_context.data[0] = '\0';
Done.

2020-09-12 19:25 UTC, andreibancioiu commented on testApp/cmd/testApp/main.go
> +	fmt.Println(string(jsonTx))
Pretty JSON (with indentation) would have been prettier :)

2020-09-12 20:06 UTC, mihaib79 commented on testApp/cmd/testApp/main.go
> +	fmt.Println(string(jsonTx))
This was for debug. Removed.

2020-09-12 20:07 UTC, mihaib79 commented on testApp/cmd/testApp/main.go
> +const proxyHost string = "https://api-testnet.elrond.com" // https://api-testnet.elrond.com for testnet
I changed it for debug and forgot to put it back. Fixed.

2020-09-12 20:14 UTC, mihaib79 commented on src/signTx.c
> +    os_memmove(tx_context.data + size_len, tx_context.data, len);
Commented.

2020-09-12 20:15 UTC, mihaib79 commented on src/signTx.c
> +        if (base64[b64len - 1] == '=')
🤷‍♂️

2020-09-12 20:18 UTC, mihaib79 commented on src/signTx.c
> +    str_size[9] = tx_context.data_size / 100 + 48;
I've been looking into it a while ago and if I remember correctly, there's a problem into the SDK :-(

2020-09-12 20:22 UTC, mihaib79 commented on src/signTx.c
> +                encoded[MAX_DISPLAY_DATA_SIZE - 4] = 'L';
Done.

2020-09-13 12:34 UTC, ccorcoveanu commented on src/base64.h
> +static bool base64decode(char *decoded, char *source, size_t len);
Why is this his declared two times?

2020-09-13 12:34 UTC, ccorcoveanu commented on src/base64.h
> +        if (decoded[i] < 32 || decoded[i] > 126) {
So, for contract deployments we will only see ‘???’? Then again, given the limitation for the tx size, we can’t really deploy real world contracts with the ledger app, right? I am thinking only if we should document this somehow so everybody is aware of this limitation

2020-09-13 12:52 UTC, mihaib79 commented on src/base64.h
> +static bool base64decode(char *decoded, char *source, size_t len);
One of them should have been base64decode_byte. Fixed.

2020-09-13 12:54 UTC, mihaib79 commented on src/base64.h
> +        if (decoded[i] < 32 || decoded[i] > 126) {
It's only a display issue, that would not impact the actual transaction signing.

2020-09-14 07:07 UTC, andreibancioiu approved these changes

2020-09-14 07:17 UTC, ccorcoveanu submitted a review, later dismissed

2020-09-14 09:36 UTC, AdoAdoAdo requested changes

2020-09-14 09:36 UTC, AdoAdoAdo commented on src/base64.h
> +            if (c == '=') {
is this if clause required? I see that base64decode_byte(c) would return 0 for '=' as well

2020-09-14 10:52 UTC, mihaib79 commented on src/base64.h
> +            if (c == '=') {
Removed.

2020-09-14 10:55 UTC, mihaib79 commented on src/base64.h
> +static bool base64decode(char *decoded, char *source, size_t len);
Fixed now.

2020-09-14 10:55 UTC, AdoAdoAdo approved these changes

2020-09-14 10:56 UTC, andreibancioiu approved these changes

2020-09-14 10:56 UTC, merged