add support for multiple accounts / address indexes
ElrondNetwork/ledger-elrond pull request #19
Opened 2020-09-16 19:59 UTC by mihaib79

- added support for selecting different accounts / address indexes
- fixed a big / little endian encoding issue

2020-09-30 11:13 UTC, andreibancioiu submitted a review, later dismissed

2020-10-08 12:10 UTC, andreibancioiu requested changes

2020-10-08 12:10 UTC, andreibancioiu commented on testApp/cmd/testMsgSign/main.go
> +	txSingleSigner := &singlesig.Ed25519Signer{}
You can extract signature verification to a separate function (optional) - since it's not production code anyway (just an extra check).

2020-10-08 12:10 UTC, andreibancioiu commented on testApp/ledger/nanos.go
> +func (n *NanoS) SignMsg(msg string) (sig []byte, err error) {
We have to reproduce this function in the web wallet as well, right? Perhaps add name for constants?

2020-10-08 12:10 UTC, andreibancioiu commented on src/signMsg.c
> +        for (index = 1; (((index * base) <= msg_context.len) &&
Tricky code. Perhaps add some comments / extract to separate function?

2020-10-08 14:53 UTC, mihaib79 commented on src/globals.c
> +unsigned char bip32_account;
The derivation path sections are: m’ / purpose’ / coin_type’ / account’ / change’ / address_index’
Therefore I went with naming the variables `bip32_account` and `bip32_address_index`

2020-10-08 14:55 UTC, mihaib79 commented on src/menu.c
> -        viewAddressAsBech32(N_storage.setting_account, N_storage.setting_address_index);
We decided to remove the 'View address' submenu as it might cause confusion when a different account is selected.

2020-10-08 14:57 UTC, mihaib79 commented on src/signMsg.h
> +    char strhash[65];
Correct. I've implemented this feature in the same way Ethereum has.
If desired I can display the first max 48 chars from the message. Right now I display the hash.

2020-10-08 15:07 UTC, mihaib79 commented on src/setAddress.c
> +    if (dataLength != sizeof(uint32_t) * 2) {
It is used when we validate its value.

2020-10-08 15:09 UTC, mihaib79 commented on src/signMsg.c
> +    uint8_t tx = 0;
tx = transmit (rx = receive)
In this case `tx` holds the number of bytes to be transmitted.

2020-10-08 15:10 UTC, mihaib79 commented on src/signMsg.c
> +            cx_eddsa_sign(&privateKey, CX_RND_RFC6979 | CX_LAST, CX_SHA512, msg_context.hash, 32, NULL, 0, msg_context.signature, 64, NULL);
`msg_context.len` is the remaining length of the message (uint32).
32 is the hash length.

2020-10-08 15:30 UTC, mihaib79 commented on testApp/cmd/testMsgSign/main.go
> +	txSingleSigner := &singlesig.Ed25519Signer{}
Done

2020-10-08 15:31 UTC, mihaib79 commented on testApp/ledger/nanos.go
> +func (n *NanoS) SignMsg(msg string) (sig []byte, err error) {
Done

2020-10-08 15:31 UTC, mihaib79 commented on src/signMsg.c
> +        for (index = 1; (((index * base) <= msg_context.len) &&
Done

2020-10-08 18:55 UTC, andreibancioiu reviewed
Will approve after all reviews, and after some manual testing.

2020-10-09 11:48 UTC, ccorcoveanu requested changes

2020-10-09 11:48 UTC, ccorcoveanu commented on src/globals.h
> +#define COIN_TYPE_eGLD      508UL
I would still have `COIN_TYPE_EGLD`, since it's a constant, to keep all uppercase

2020-10-09 11:48 UTC, ccorcoveanu commented on src/signMsg.c
> +        for (index = 1; (((index * base) <= msg_context.len) &&
Pushed?

2020-10-09 12:26 UTC, mihaib79 commented on src/globals.h
> +#define COIN_TYPE_eGLD      508UL
Done

2020-10-09 12:34 UTC, ccorcoveanu approved these changes

2020-10-11 21:07 UTC, AdoAdoAdo requested changes

2020-10-11 21:07 UTC, AdoAdoAdo commented on testApp/cmd/testMsgSign/main.go
> +	_suite := ed25519.NewEd25519()
please remove _ from variable name

2020-10-11 21:07 UTC, AdoAdoAdo commented on testApp/cmd/testMsgSign/main.go
> +	publicKey, _ := keyGen.PublicKeyFromByteArray(bytes)
can you treat the errors here and above in decode and convertBits (return the err if !=nil)

2020-10-12 06:18 UTC, mihaib79 commented on src/signMsg.c
> +            (((index * base) / base) == index));
Correct

2020-10-12 06:54 UTC, mihaib79 commented on testApp/cmd/testMsgSign/main.go
> +	_suite := ed25519.NewEd25519()
Done

2020-10-12 06:54 UTC, mihaib79 commented on testApp/cmd/testMsgSign/main.go
> +	publicKey, _ := keyGen.PublicKeyFromByteArray(bytes)
Done

2020-10-12 07:49 UTC, AdoAdoAdo approved these changes

2020-10-12 17:56 UTC, mihaib79 commented on src/signMsg.c
> +        for (index = 1; (((index * base) <= msg_context.len) &&
Not changed for easier review, as discussed.

2020-10-13 05:59 UTC, AdoAdoAdo approved these changes

2020-10-13 06:30 UTC, ccorcoveanu approved these changes

2020-10-13 06:42 UTC, andreibancioiu approved these changes

2020-10-13 06:44 UTC, merged