add tx hash signing feature
ElrondNetwork/ledger-elrond pull request #21
Opened 2020-10-26 12:27 UTC by mihaib79

Added tx hash signing (tx version 2).
Added the possibility to select uint32 accounts and addresses indexes for backwards compatibility.

2020-10-29 11:12 UTC, AdoAdoAdo requested changes

2020-10-31 20:03 UTC, mihaib79 commented on src/main.c
> +                    // G_io_apdu_buffer[1] = bip32_account;
To emphasize that those fields are not to be taken into account anymore since now those variables are 32 bit long, but we still expect 6 bytes transmitted to maintain compatibility with the web wallet. The respective values (account and address_index) should now me read with the help of the getAddress function. If you consider the comments unnecessary, I will remove them.

2020-10-31 20:05 UTC, mihaib79 commented on src/signTxHash.c
> +    if (tx_hash_context.current_field_len == 0 || tx_hash_context.current_value_len == 0)
Done, though we can't reuse them in signTx since it uses a different json parser. Besides, that part of the code was already audited, therefore I would rather not touch it.

2020-11-01 19:44 UTC, andreibancioiu commented on src/main.c
> +                    // G_io_apdu_buffer[1] = bip32_account;
Please add a comment in the code, explaining what you've explained here.

2020-11-01 19:50 UTC, andreibancioiu approved these changes

2020-11-01 19:52 UTC, andreibancioiu approved these changes
In the future, we might want to have shorter (and more) git commits - so that code movement & refactoring is tracked a bit easier. :pray:

2020-11-02 08:32 UTC, AdoAdoAdo commented on src/main.c
> +                    // G_io_apdu_buffer[1] = bip32_account;
I would rather add a comment explaining that the account and address index should be obtained with getAddress function instead and remove commented out code

2020-11-02 08:44 UTC, mihaib79 commented on src/main.c
> +                    // G_io_apdu_buffer[1] = bip32_account;
Done

2020-11-02 08:47 UTC, AdoAdoAdo requested changes

2020-11-02 08:47 UTC, AdoAdoAdo commented on src/signTxHash.c
> +    err = verify_value(&valid_field);
is valid_field really necessary as a parameter?
you anyway exit on err != MSG_OK, so I think you can drop it, as it seems to somewhat duplicate the return of the function.

2020-11-02 08:52 UTC, mihaib79 commented on src/signTxHash.c
> +    err = verify_value(&valid_field);
If the parsed field is not found in any of the "verify" functions, the result would be MSG_OK, though that would mean the field is unknown (not valid). Therefore, when the field is found AND verified, I set the valid_field to true.

2020-11-03 05:59 UTC, AdoAdoAdo approved these changes

2020-11-03 13:12 UTC, andreibancioiu approved these changes

2020-11-04 08:21 UTC, merged