stake and tx fee fixes
ElrondNetwork/ledger-elrond pull request #28
Opened 2021-02-03 15:20 UTC by bogdan-rosianu

2021-02-04 09:45 UTC, AdoAdoAdo requested changes

2021-02-04 09:56 UTC, bogdan-rosianu commented on src/signTx.c
> +    uint128_t gasForData;
done

2021-02-05 08:12 UTC, AdoAdoAdo requested changes

2021-02-05 08:12 UTC, AdoAdoAdo commented on src/signTx.c
> +    mul128(&x, &y, &z); /* XXX: there is a one-byte overflow in tostring128(), hence size-1 */
isn't this supposed to be mul128(&x, &z, &y)?

2021-02-05 08:13 UTC, AdoAdoAdo approved these changes

2021-02-05 08:13 UTC, AdoAdoAdo commented on src/signTx.c
> +    mul128(&x, &y, &z); /* XXX: there is a one-byte overflow in tostring128(), hence size-1 */
and the of course tostring128 (&y,....

2021-02-05 08:16 UTC, AdoAdoAdo requested changes
sorry, I approved by mistake

2021-02-05 08:17 UTC, bogdan-rosianu commented on src/signTx.c
> +    mul128(&x, &y, &z); /* XXX: there is a one-byte overflow in tostring128(), hence size-1 */
no. 
```
txFEE = gasUnitForMoveBalance * GASPRICE + (gasLimit - gasUnitForMoveBalance) * gasPriceModifier * GASPRICE
``` 
let's make some renamings:
txFEE = `a * b + (c - a) * d * b` which is equal to `b[a + (c-a)*d]` (with the difference that instead of `*gas_price_modifier` we use `/gas_price_divider`. 
long story short, the line is correct

2021-02-05 08:28 UTC, AdoAdoAdo commented on src/signTx.c
> +    mul128(&x, &y, &z); /* XXX: there is a one-byte overflow in tostring128(), hence size-1 */
somehow I missed line 118
right, then it looks ok.

2021-02-05 08:31 UTC, AdoAdoAdo approved these changes

2021-02-05 08:53 UTC, merged