bring latest changes to master
ElrondNetwork/ledger-elrond pull request #30
Opened 2021-02-16 12:17 UTC by bogdan-rosianu

2021-02-22 17:11 UTC, mihaib79 commented on src/signTxHash.c
>      valid_field |= strncmp(tx_hash_context.current_field, NONCE_FIELD, strlen(NONCE_FIELD)) == 0;
We should add here checks for username fields (sender / receiver).

2021-03-08 07:30 UTC, AdoAdoAdo requested changes

2021-03-08 07:30 UTC, AdoAdoAdo commented on src/viewAppVersion.c
> +#include "menu.h"
why is this required? there is no other code change in this file

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/main.c
> +                    // sign tx is deprecated is this version and hash signing should be used
done

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/signMsg.c
> +#include "utils.h"
it was a lint issue fixed by the Ledger team so we merged those changes into our repo

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/signTxHash.c
> +        return err;
done

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/signTxHash.c
> +                    tx_hash_context.data_field_size = tx_hash_context.data_field_size / 4 * 3;
for converting the `base64` encoded data length into decoded `string` length. Same logic as before, only moved

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/utils.c
> +    // txFEE = gasUnitForMoveBalance * GASPRICE + (gasLimit - gasUnitForMoveBalance) * gasPriceModifier * GASPRICE
updated comment

2021-03-08 08:37 UTC, bogdan-rosianu commented on src/viewAppVersion.c
> +#include "menu.h"
same reason as above. linter issue found by Ledger team

2021-03-10 08:58 UTC, AdoAdoAdo requested changes

2021-03-10 09:02 UTC, mihaib79 submitted a review, later dismissed

2021-03-10 09:43 UTC, bogdan-rosianu commented on src/signTxHash.c
> +                        data_value_len = tx_hash_context.current_value_len / 4 * 4;
done

2021-03-10 09:43 UTC, bogdan-rosianu commented on src/signTxHash.c
> +                            if(dataBuffer[idx-2] == '='){
added a comment to explain the reasoning

2021-03-11 07:13 UTC, AdoAdoAdo approved these changes

2021-03-11 07:17 UTC, mihaib79 approved these changes

2021-03-11 12:39 UTC, merged