Esdt tokens support
ElrondNetwork/ledger-elrond pull request #41
Opened 2021-06-28 15:15 UTC by bogdan-rosianu

2021-06-29 15:08 UTC, mariusmihaic reviewed
Looks fine. However, variables and function names use **snake_case** and **camelCase** interchangeably.

2021-07-01 12:18 UTC, AdoAdoAdo commented on testApp/cmd/testESDT/main.go
> +	// "github.com/ethereum/go-ethereum/crypto/secp256k1"
remove commented import

2021-07-01 12:28 UTC, AdoAdoAdo commented on testApp/cmd/testESDT/main.go
> +	"github.com/decred/dcrd/dcrec/secp256k1"
can we use github.com/btcsuite/btcd/btcec instead?

as it has secp256k1 support and you already use bech32 from btcsuite

2021-07-01 12:45 UTC, AdoAdoAdo commented on testApp/cmd/testESDT/main.go
> +const proxyHost string = "https://testnet-gateway.elrond.com"
seems like most of the functions, constants, variables, types are duplicated with the ones in testApp/main.go

Can you extract all common types, constants, variables, functions into a separate file e.g testApp/cmd/common/testsCommon.go ?

and then refactor the main.go from both cmd/testESDT and cmd/testApp to remove the duplicated code by calling the common functions instead.

2021-07-06 08:31 UTC, AdoAdoAdo approved these changes

2021-07-06 11:22 UTC, bogdan-rosianu commented on src/signTxHash.c
> +    bool is_mainnet_transaction = strncmp(tx_context.chain_id, esdt_info.chain_id, MAX_CHAINID_LEN) == 0;
not related to mainnet. this check only verifies if the same chain ID has been used when preparing ESDT data. please rename

2021-07-06 11:22 UTC, bogdan-rosianu commented on src/viewAppVersion.c
> +    (void)(button_mask_counter);
is this related to a linter issue?

2021-07-06 11:22 UTC, bogdan-rosianu commented on testApp/cmd/common/testscommon.go
> +var TestPkBytes = []byte{0xb5, 0xe3, 0xcf, 0xb4, 0x42, 0xb0, 0xac, 0xad, 0xf5, 0xf5, 0xd1, 0xed, 0x1f, 0x7a, 0xc7, 0xb6,
this is a sk, isn't it?

2021-07-06 11:30 UTC, AdoAdoAdo commented on src/signTxHash.c
> +    bool is_mainnet_transaction = strncmp(tx_context.chain_id, esdt_info.chain_id, MAX_CHAINID_LEN) == 0;
right, fixed

2021-07-06 11:31 UTC, AdoAdoAdo commented on src/viewAppVersion.c
> +    (void)(button_mask_counter);
removed unused param warning.

2021-07-06 11:34 UTC, AdoAdoAdo commented on testApp/cmd/common/testscommon.go
> +var TestPkBytes = []byte{0xb5, 0xe3, 0xcf, 0xb4, 0x42, 0xb0, 0xac, 0xad, 0xf5, 0xf5, 0xd1, 0xed, 0x1f, 0x7a, 0xc7, 0xb6,
right, renamed

2021-07-06 11:35 UTC, AdoAdoAdo commented on src/constants.h
> +#define ERR_INDEX_OUT_OF_BOUNDS    0x6E13
I would leave it as it is for now, without defining it in the other repos, as this is not a user error.

2021-07-06 12:15 UTC, mariusmihaic commented on src/signTxHash.c
> +    if (has_data && identifier_len_valid && has_esdt_transfer_prefix && has_registered_esdt_identifier && same_chainid) {
Maybe change the code here to avoid some possible undefined behavior.
`esdt_info.identifier_len` and `tx_context.data` are used without being checked if they are valid.  Check `has_data` and `identifier_len_valid` before using structure fields 

```suggestion
    bool identifier_len_valid = esdt_info.identifier_len > 0;
    bool has_data = strlen(tx_context.data) > 0;
    
    if (has_data && identifier_len_valid)
    {
        bool has_esdt_transfer_prefix = strncmp(tx_context.data + DATA_SIZE_LEN - 1, ESDT_TRANSFER_PREFIX, strlen(ESDT_TRANSFER_PREFIX)) == 0;
         bool has_registered_esdt_identifier = strncmp(tx_context.data + DATA_SIZE_LEN - 1 + strlen(ESDT_TRANSFER_PREFIX), esdt_info.identifier, esdt_info.identifier_len) == 0;
         bool same_chainid = strncmp(tx_context.chain_id, esdt_info.chain_id, MAX_CHAINID_LEN) == 0;
    
         if (has_esdt_transfer_prefix && has_registered_esdt_identifier && same_chainid) {
    }
    
```

2021-07-06 12:17 UTC, mariusmihaic requested changes
Just a minor modification

2021-07-06 12:17 UTC, mariusmihaic commented on src/provideESDTInfo.h
> +static const uint8_t LEDGER_SIGNATURE_PUBLIC_KEY[] = {
Just a question for myself: 
Why is this not correct?

2021-07-06 12:20 UTC, raduchis submitted a review, later dismissed

2021-07-06 12:22 UTC, AdoAdoAdo commented on src/provideESDTInfo.h
> +static const uint8_t LEDGER_SIGNATURE_PUBLIC_KEY[] = {
this public key was used for testing, we need the correct one.

2021-07-06 12:47 UTC, raduchis approved these changes

2021-07-06 12:50 UTC, mariusmihaic submitted a review, later dismissed

2021-07-13 11:04 UTC, mariusmihaic submitted a review, later dismissed

2021-07-13 11:22 UTC, AdoAdoAdo submitted a review, later dismissed

2021-07-14 14:16 UTC, AdoAdoAdo approved these changes

2021-07-14 14:22 UTC, mariusmihaic approved these changes

2021-07-14 14:23 UTC, merged