Get address auth token
ElrondNetwork/ledger-elrond pull request #44
Opened 2021-07-30 07:50 UTC by bogdan-rosianu

Implemented a mechanism that receiver the account and the address index, alongside a message (token) to be signed. This is helpful for generating authorized user sessions with a single interaction with the Ledger device.

Also, refactored `getAddress` in order to use common functions with the new mechanism from a common file.

2021-07-30 11:30 UTC, mariusmihaic requested changes
Please see comments.

Also note that comments with [comment] tag don't necessary mean that an action has to be taken (e.g.: change/modify, etc.), but rather represent a suggestion/opinion/question.

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +        }
1. `((index * base) / base) == index` will always be true, right?
2. I understand you use base = 10, but is it safe to store the result of a divide operation in an int variable (e.g.: `index /= base` or `(full_message_len / index) % base`)?
3. You use **first** `for loop` to compute `index *= base`, then **second** `for loop` to compute the opposite `index /= base`. Perhaps you can compress this logic in a **single** `for loop`
4. Optional, if you think that this functionality can be reused and it makes sense, you can extract this code in a separate utility function

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +        THROW(MSG_OK);
Usually, you use THROW to signal that an exception happened and you want to interrupt the execution.
It is unusual to throw an exception that is actually an "OK" message-> finished with success.

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +            cx_eddsa_sign(&privateKey, CX_RND_RFC6979 | CX_LAST, CX_SHA512, token_auth_context.hash, 32, NULL, 0, token_auth_context.signature, 64, NULL);
I think it would make sens here and every other place to use constants instead of magic numbers like 32, 64, etc

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +    const uint8_t response_size = strlen(token_auth_context.address) + 64;
```suggestion
    const uint8_t response_size = strlen(complete_response)
```

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +    uint8_t tx = 0;
[comment]
Usually tx <=> transaction. Perhaps change its name to explain its meaning?

2021-07-30 11:30 UTC, mariusmihaic commented on src/signMsgAuthToken.c
> +void update_token_display_data(uint8_t *data_buffer, uint8_t data_length) {
Usually, when setting function parameters (especially mixed input/output) you specify their intent by using const, e.g. here they are only used as input, not modified:

```suggestion
void update_token_display_data(uint8_t const *data_buffer, uint8_t const data_length) {
```

2021-07-30 12:14 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +#include "getPrivateKey.h"
the file name resembles the function name that it handles. I will leave it as it is. 
However, renamed all files to snake case style

2021-07-30 12:15 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +    }
I couldn't tell.. @mihaib79  ?

2021-07-30 12:17 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +void get_address_hex_from_binary(uint8_t *publicKey, char *address) {
it is now specific for addresses (the 64 index and stuff). we could definitely extract it to a more general function when needed

2021-07-30 12:18 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +bool get_public_key(uint32_t accountNumber, uint32_t index, uint8_t *publicKeyArray) {
done

2021-07-30 12:19 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +    bech32EncodeFromBytes(address, hrp, buffer, 33);
`bech32EncodeFromBytes` it's fetched from deps, so I cannot change it's name

2021-07-30 12:21 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +    hrp = HRP;
removed the redundant assignment. Regarding the `33` size, maybe @mihaib79 can help

2021-07-30 12:22 UTC, bogdan-rosianu commented on src/addressHelpers.h
> +void get_address_bech32_from_binary(uint8_t *publicKey, char *address);
done

2021-07-30 12:23 UTC, bogdan-rosianu commented on src/addressHelpers.c
> +void get_address_bech32_from_binary(uint8_t *publicKey, char *address) {
I will leave it as it is. the fact that it handles the HRP logic is enough so it can be considered a standalone function

2021-07-30 12:24 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +bool sign_auth_token(void);
done

2021-07-30 12:24 UTC, bogdan-rosianu commented on src/signMsgAuthToken.h
> +void init_msg_context(void);
removed

2021-08-02 07:35 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +        address_index = read_uint32_be(data_buffer + sizeof(uint32_t));
done

2021-08-02 07:41 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +        update_token_display_data(data_buffer, data_length);
added comments in regards to the data buffer structure and the addition and deletions to the length / buffer address

2021-08-02 08:16 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +        }
extracted to a common function. can be refactored later

2021-08-02 08:18 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +        THROW(MSG_OK);
no. if you look in `main.c` there are many places where MSG_OK is thrown. in this case, it is used to indicate the caller that the bulk part has been processed so it can continue with the next bulk. I will leave it as it is

2021-08-02 08:32 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +            cx_eddsa_sign(&privateKey, CX_RND_RFC6979 | CX_LAST, CX_SHA512, token_auth_context.hash, 32, NULL, 0, token_auth_context.signature, 64, NULL);
done, defined constants

2021-08-02 08:42 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +    const uint8_t response_size = strlen(token_auth_context.address) + 64;
it won't work as expected so I will leave it as it is

2021-08-02 08:44 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +    uint8_t tx = 0;
the naming is Ledger specific. Will leave it as it is

2021-08-02 08:45 UTC, bogdan-rosianu commented on src/signMsgAuthToken.c
> +void update_token_display_data(uint8_t *data_buffer, uint8_t data_length) {
done

2021-08-02 11:28 UTC, mariusmihaic commented on src/utils.c
> +void uint32_t_to_char_array(uint32_t const input, char *output) {
Regarding previous comments:

> 1. `((index * base) / base) == index` will always be true, right?
> 2. I understand you use base = 10, but is it safe to store the result of a divide operation in an int variable (e.g.: `index /= base` or `(full_message_len / index) % base`)?
> 3. You use **first** `for loop` to compute `index *= base`, then **second** `for loop` to compute the opposite `index /= base`. Perhaps you can compress this logic in a **single** `for loop`

At least please add a TODO here, since this should be refactored.

2021-08-02 11:28 UTC, mariusmihaic commented on src/address_helpers.c
> +}
IMHO this function is still redundant.
You use a `buffer` to copy the `public_key` and call `bech32EncodeFromBytes`.

Why not just call `bech32EncodeFromBytes(address, HRP, public_key, PUBLIC_KEY_LEN)` ? , where `PUBLIC_KEY_LEN = 32 U`
Also, that 33 magic number looks fishy, since the null terminator is set on position 32

2021-08-02 11:28 UTC, mariusmihaic commented on src/address_helpers.c
> +void get_address_hex_from_binary(uint8_t *public_key, char *address) {
Regarding previous comment:

> This functionality can be reused in other places as well, it doesn't have to be "tied" to hex->binary for addresses.
I would extract this functionality in a separate more generic function which returns hex format from a binary (probably also move this function in a different file, e.g.: **utils.h/hex.h** ). For this, you would also need to provide the length of the input, e.g.:

```c++
void binary_to_hex(char const *in, uint64_t const len, char *out) 
```

In `parse_tx`  file there is already a utility function called `parse_hex` which does the opposite of this. I still think it would make sense to make this function more generic and move these utilities in a separate file(e.g.: `hex.h`).  

Conclusion: At least please add a **TODO** here to refactor this

2021-08-02 11:46 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +            cx_eddsa_sign(&privateKey, CX_RND_RFC6979 | CX_LAST, CX_SHA512, token_auth_context.hash, 32, NULL, 0, token_auth_context.signature, SIGNATURE_LEN, NULL);
done

2021-08-02 11:47 UTC, bogdan-rosianu commented on src/constants.h
> +#define HASH_LEN              32
the same length is used for both `sha256` and `sha3` so it is ok

2021-08-02 11:55 UTC, bogdan-rosianu commented on src/constants.h
> +#define SIGNATURE_LEN         64
good point. there are situations where the signature can have a different length. renamed to `MESSAGE_SIGNATURE_LEN` so we tie this constant to a particular feature, not an algorithm.

2021-08-02 11:55 UTC, bogdan-rosianu commented on src/sign_msg.c
>      char strhash[65];
it is basically the hash hex encoded + the `\0` so used `2 * HASH_SIZE + 1`

2021-08-02 11:55 UTC, bogdan-rosianu commented on src/sign_msg.c
> +           4 bytes      <message length> bytes
renamed to `message`. thanks

2021-08-02 12:06 UTC, bogdan-rosianu commented on src/sign_msg.c
>          cx_keccak_init(&sha3_context, 256);
added

2021-08-02 12:07 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
>          token_auth_context.token[0] = '\0';
to make sure the `strlen` will work as expected. just for safety

2021-08-02 12:11 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
>          uint8_t public_key[32];
extracted const

2021-08-02 12:12 UTC, bogdan-rosianu commented on src/address_helpers.c
> +}
@mihaib79  ?

2021-08-02 12:26 UTC, mariusmihaic commented on src/constants.h
> +#define PUBLIC_LEY_LEN        32
Did you mean?
```suggestion
#define PUBLIC_KEY_LEN        32
```

2021-08-02 12:31 UTC, bogdan-rosianu commented on src/utils.c
> +void uint32_t_to_char_array(uint32_t const input, char *output) {
added a todo

2021-08-02 12:32 UTC, bogdan-rosianu commented on src/constants.h
> +#define PUBLIC_LEY_LEN        32
fixed, thanks

2021-08-02 14:00 UTC, mariusmihaic commented on src/get_address.c
> +    uint8_t publicKey[PUBLIC_LEY_LEN];
```suggestion
    uint8_t public_key[PUBLIC_LEY_LEN];
```

2021-08-02 14:19 UTC, bogdan-rosianu commented on src/get_address.c
> +    uint8_t publicKey[PUBLIC_LEY_LEN];
done

2021-08-02 14:23 UTC, mariusmihaic submitted a review, later dismissed

2021-08-02 17:07 UTC, mihaib79 requested changes

2021-08-02 17:07 UTC, mihaib79 commented on src/sign_msg.c
> +    ux_flow_init(0, ux_sign_msg_flow, NULL);
why did you change the order of these two lines ?
in the Ledger's sample app, setting the asynch flag is done just before exiting the function.

2021-08-02 17:07 UTC, mihaib79 commented on src/address_helpers.c
> +    if (!getPrivateKey(account_number, index, &private_key)) {
please change this to get_private_key for consistency

2021-08-02 17:07 UTC, mihaib79 commented on src/sign_msg_auth_token.c
> +    if (!getPrivateKey(bip32_account, bip32_address_index, &privateKey)) {
please change this to get_private_key for consistency

2021-08-02 17:07 UTC, mihaib79 commented on src/sign_msg_auth_token.c
> +    cx_ecfp_private_key_t privateKey;
please rename to private_key for consistency

2021-08-03 10:44 UTC, bogdan-rosianu commented on src/sign_msg.c
> +    ux_flow_init(0, ux_sign_msg_flow, NULL);
fixed. also, fixed for sign tx hash

2021-08-03 10:44 UTC, bogdan-rosianu commented on src/address_helpers.c
> +    if (!getPrivateKey(account_number, index, &private_key)) {
done

2021-08-03 10:45 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    if (!getPrivateKey(bip32_account, bip32_address_index, &privateKey)) {
done

2021-08-03 10:45 UTC, bogdan-rosianu commented on src/sign_msg_auth_token.c
> +    cx_ecfp_private_key_t privateKey;
done

2021-08-04 10:08 UTC, mihaib79 approved these changes

2021-08-04 10:08 UTC, mihaib79 approved these changes

2021-08-11 12:45 UTC, mihaib79 approved these changes

2021-08-11 15:32 UTC, merged